title: "BioComputingUP News"
email: biocomp@bio.unipd.it
timezone: UTC
baseurl: ""
permalink: "/:year/:month/:day/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon-16x16.png'
author: Sal
paginate: 30
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
#ganalytics: s

# Authors
authors:
  andras:
    name: Hatos András
    display_name: Hatos András
    email: andras.hatos@unipd.it
    description: ""

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
